import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p className="bg-blue-200">layout atas</p>
        {children}
        <p className="bg-blue-200">layout bawah</p>
      </body>
    </html>
  );
}
